spring:
  application:
    name: process
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true