apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-process-deployment
  labels:
    app: order-process
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-process
  template:
    metadata:
      labels:
        app: order-process
    spec:
      containers:
        - name: order-process
          image: docker-repo/order-process:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-config
                  key: mail.host
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-config
                  key: mail.port
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-config
                  key: mail.username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-config
                  key: mail.password
